json.id recommendation.id
json.category recommendation.category_pretty
json.name recommendation.name
json.trip_id recommendation.trip_id
json.city_id recommendation.city_id
json.trip recommendation.trip
json.user recommendation.trip.user
json.latitude recommendation.latitude
json.longitude recommendation.longitude
json.icon_image recommendation.icon_image
json.main_url recommendation.main_url